import 'package:test/test.dart';
import 'day07.dart';

void main() {
  const tachyonManifold = '''
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
''';

  group('Part1', () {
    test('sample', () {
      expect(part1(tachyonManifold), equals(21));
    });
  });

  group('Part2', () {
    test('sample', () {
      expect(part2('test'), equals(0));
    });
  });
}
